development:
  adapter: postgresql
  encoding: utf8
  database: bostons_bad_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: bostons_bad_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: bostons_bad_production
  pool: 5
  password: